org: rdominguez
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
plugins:
  - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  holaMundo:
    handler: index.holaMundo
    events:
      - httpApi:
          path: /holamundo/{nombre}
          method: get
  crearUsuario:
    handler: index.crearUsuario
    events:
      - httpApi:
          path: /usuario
          method: POST

